version: "3.10"

services:
  app:
    image: bradyin/edu-web:web
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongonetwork
  mongodb:
    image: bradyin/edu-web:mongo
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongonetwork
volumes:
  mongodata:
networks:
  mongonetwork:

