FROM python:3.11

WORKDIR /web-app 

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY  . .

RUN pip install pipenv

RUN pipenv install

EXPOSE 5001

CMD [ "pipenv", "run", "python", "app.py"]
