name: Web deploy (CI/CD)

on:
  push: 
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    # - name: Test
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pipenv
    #     pipenv install --dev
    #     pipenv run pytest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKERHUB_USER }}/edu-web 
    - name: Push Docker image
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose push